// Single import choke-point for the 200-vehicle dataset. Everything that
// touches inventory imports `VEHICLES` from here so the path to the JSON
// (and the cast to `Vehicle[]`) lives in exactly one place.
//
// The JSON is generated by `scripts/generate_vehicles.mjs` and treated as
// immutable per CLAUDE.md — we trust its shape and cast rather than running
// a parser at startup.

import type { Vehicle } from '../types/vehicle';
import data from '../../data/vehicles.json';

export const VEHICLES: readonly Vehicle[] = data as Vehicle[];
